# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Check code

on:
  pull_request:
    branches:
      - master

jobs:
  test:
    name: Check code
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      - name: Install dependencies
        run: yarn install
      - name: Run tests
        run: yarn test
      - name: Check build
        run: yarn build
